# Generated by Django 4.1.1 on 2022-10-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasiya', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
