# Generated by Django 4.1.1 on 2022-10-14 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0002_alter_mahsulot_kelgan_sana_alter_mahsulot_olchov'),
        ('userapp', '0002_remove_sotuvchi_vazifa_remove_sotuvchi_user_and_more'),
        ('statsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistika',
            name='jami',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='statistika',
            name='mahsulot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiyapp.mahsulot'),
        ),
        migrations.AddField(
            model_name='statistika',
            name='mijoz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiyapp.mijoz'),
        ),
        migrations.AddField(
            model_name='statistika',
            name='miqdor',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='statistika',
            name='sotuvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.sotuvchi'),
        ),
        migrations.AddField(
            model_name='statistika',
            name='tolandi',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
