# Generated by Django 4.1.1 on 2022-11-19 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0002_remove_sotuvchi_vazifa_remove_sotuvchi_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuvchi',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
